# Generated by Django 3.2.3 on 2021-05-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='conatct',
            field=models.IntegerField(),
        ),
    ]
