# Generated by Django 3.2.3 on 2021-05-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_alter_student_conatct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='conatct',
            new_name='contact',
        ),
    ]
